### ISSUE TITLE
different terms, symbols and analogies by protagonist

### ISSUE THREAD

**Issue by henkvancann** [tno-terminology-design/design-methods#1]
[Here](https://tno-terminology-design.github.io/design-methods/docs/methods/criteria-elicitation#issuesexceptions) I would say under point 2. that the protagonist could also do her/his best to explain the concepts/terms the participants do not yet know what they are, in different terms, symbols and analogies and so on.

**Comment by RieksJ** [comment]
While I agree that protagonists should do their best to explain stuff, (a) I don't think this is the right place, and (b) all texts need to be updated to reflect the current insights (this is maintenance that I haven't got to yet, and I suspect that will remain for some time to come as we focus on the tools while we have some programming support for that).
